In [1]:
%load_ext autoreload
%autoreload 2

In [3]:
import pandas as pd
from farmbase.config import settings
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from sqlalchemy.orm import sessionmaker

In [4]:
df = pd.read_csv("data/kamis_market_prices.csv")

# Replace all cells that contain only "-" (with or without surrounding whitespace) with None
df.replace(r"^\s*-\s*$", pd.NA, regex=True, inplace=True)


def split_price_column(df, column, prefix):
    """Split a 'price/unit' column into price, unit, and currency."""
    split_cols = df[column].str.split("/", expand=True)
    df[f"{prefix}_price"] = pd.to_numeric(split_cols[0], errors="coerce")
    df[f"{prefix}_unit"] = split_cols[1]
    df[f"{prefix}_ccy"] = "KES"
    return df


# Apply transformations
df = split_price_column(df, "Wholesale", "wholesale")
df = split_price_column(df, "Retail", "retail")

# Drop the original columns
df.drop(columns=["Wholesale", "Retail", "source_date"], inplace=True)
df

,Market,Commodity,Classification,Grade,Sex,Supply Volume,County,Date,wholesale_price,wholesale_unit,wholesale_ccy,retail_price,retail_unit,retail_ccy
0,Awendo,Beans (Mwezi Moja),<NA>,<NA>,<NA>,5000.0,Migori,2021-05-24,60.00,Kg,KES,68.89,Kg,KES
1,Awendo,Beans (Canadian wonder),<NA>,<NA>,<NA>,8000.0,Migori,2021-05-24,71.11,Kg,KES,75.56,Kg,KES
2,Awendo,Fertilizer,NPK,<NA>,<NA>,1800.0,Migori,2021-05-24,36.00,Kg,KES,40.00,Kg,KES
3,Awendo,Fertilizer,NPK,<NA>,<NA>,2500.0,Migori,2021-05-24,48.00,Kg,KES,54.00,Kg,KES
4,Awendo,Fertilizer,DAP,<NA>,<NA>,5000.0,Migori,2021-05-24,63.00,Kg,KES,68.00,Kg,KES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
911958,Kipini Fish market,Rayfish,Dried,<NA>,<NA>,22.0,Tana-River,2025-06-09,280.00,Kg,KES,350.00,Kg,KES
911959,Kipini Fish market,Rabbitfish (Tafi/Tasi),Frozen/Chilled,<NA>,<NA>,24.0,Tana-River,2025-06-09,250.00,Kg,KES,330.00,Kg,KES
911960,Kipini Fish market,Fresh Water Shrimp,Dried,<NA>,<NA>,58.0,Tana-River,2025-06-09,200.00,Kg,KES,270.00,Kg,KES
911961,Kipini Fish market,Fresh Water Shrimp,Fresh,<NA>,<NA>,76.0,Tana-River,2025-06-09,100.00,Kg,KES,150.00,Kg,KES
911962,Kipini Fish market,African butter catfish,Fresh,<NA>,<NA>,31.0,Tana-River,2025-06-09,100.00,Kg,KES,160.00,Kg,KES

In [8]:
from farmbase import Commodity
from tqdm import tqdm

# Create async DB engine and session
# DATABASE_URL = "postgresql+asyncpg://user:pass@localhost/dbname"  # replace with actual
engine = create_async_engine(settings.SQLALCHEMY_DATABASE_URI, echo=True)
AsyncSessionLocal = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

df[["Commodity", "Classification", "Grade", "Sex"]]


async def populate_commodities(_com):
    async with AsyncSessionLocal() as session:
        for _, row in tqdm(_com.iterrows(), total=len(_com), desc="Inserting Commodities"):
            grade_value = None if pd.isna(row.Grade) else row.Grade
            classificatio_value = None if pd.isna(row.Classification) else row.Classification
            sex_value = None if pd.isna(row.Sex) else row.Sex.upper()
            com = Commodity(name=row.Commodity, classification=classificatio_value, grade=grade_value, sex=sex_value)
            session.add(com)
        await session.commit()
        print("✅ Finished populating commodities.")


df2 = df[["Commodity", "Classification", "Grade", "Sex"]].drop_duplicates()
df2 = df2[~df2.Commodity.isna()]

await populate_commodities(df2)

Inserting Commodities: 100%|██████████| 808/808 [00:00<00:00, 29121.35it/s]

2025-06-10 16:32:27,188 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2025-06-10 16:32:27,188 INFO sqlalchemy.engine.Engine [raw sql] ()
2025-06-10 16:32:27,194 INFO sqlalchemy.engine.Engine select current_schema()
2025-06-10 16:32:27,195 INFO sqlalchemy.engine.Engine [raw sql] ()
2025-06-10 16:32:27,198 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2025-06-10 16:32:27,199 INFO sqlalchemy.engine.Engine [raw sql] ()
2025-06-10 16:32:27,202 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-06-10 16:32:27,210 INFO sqlalchemy.engine.Engine INSERT INTO farmbase_core.commodity (name, classification, grade, sex) SELECT p0::VARCHAR, p1::VARCHAR, p2::VARCHAR, p3::gender_enum FROM (VALUES ($1::VARCHAR, $2::VARCHAR, $3::VARCHAR, $4::gender_enum, 0), ($5::VARCHAR, $6::VARCHAR, $7::VARCHAR, $8: ... 59313 characters truncated ... nter) ORDER BY sen_counter RETURNING farmbase_core.commodity.id, farmbase_core.commodity.id AS id__1
2025-06-10 16:32:27,211 INFO sqlalchemy.engine.Engine [generated in 0.00125s (insertmanyvalues) 1/1 (ordered)] ('Beans (Mwezi Moja)', None, None, None, 'Beans (Canadian wonder)', None, None, None, 'Fertilizer', 'NPK', None, None, 'Fertilizer', 'DAP', None, None, 'Fertilizer', 'CAN', None, None, 'Goat', 'East African Goat', None, 'FEMALE', 'Goat', 'East African Goat', None, 'MALE', 'Chicken', 'Improved Kienyeji', None, 'MALE', 'Chicken', 'Improved Kienyeji', None, 'FEMALE', 'Donkey', None, None, 'FEMALE', 'Donkey', None, None, 'MALE', 'Goat', 'Mixed', 'Grade 2 ', 'FEMALE', 'Chicken', 'Indigenous' ... 3132 parameters truncated ... 'Grade 2 ', 'FEMALE', 'Chicken', 'Ayrshire', None, 'MALE', 'Duck', 'Mallard', 'Grade 2', 'MALE', 'Cattle', None, 'Grade 4 ', 'CASTRATE', 'Rice', 'Yellow Maize', None, None, 'Fertilizer', 'Urea', None, None, 'Fertilizer', 'Sulphate of Ammonia', None, None, 'Queenfish (Pandu)', 'Dried', None, None, 'Dragon Fruit', None, None, None, 'Cashewnuts (Korosho)', None, None, None, 'Chicken', 'Hamshire', None, 'FEMALE', 'Fertilizer', 'Ammonia Anhydrous', None, None, 'Rabbit', 'Flemish Giant', None, 'MALE')
2025-06-10 16:32:27,272 INFO sqlalchemy.engine.Engine COMMIT
✅ Finished populating commodities.

In [25]:
# df2 = df[['Commodity', 'Classification', 'Grade', 'Sex']].drop_duplicates()
df2[~df2.Commodity.isna()].Sex.unique()

array([<NA>, 'Female', 'Male', 'Castrate'], dtype=object)

In [9]:
from farmbase.market.models import Market

markets = pd.read_csv("markets.csv")

# Create async DB engine and session
# DATABASE_URL = "postgresql+asyncpg://user:pass@localhost/dbname"  # replace with actual
engine = create_async_engine(settings.SQLALCHEMY_DATABASE_URI, echo=True)
AsyncSessionLocal = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)


async def populate_markets(_markets):
    async with AsyncSessionLocal() as session:
        for _, row in tqdm(_markets.iterrows(), total=len(_markets), desc="Inserting Markets"):
            region = Market(name=row.market, location=f"POINT({row.lon} {row.lat})")
            session.add(region)
        await session.commit()
        print("✅ Finished populating markets.")


await populate_markets(markets)

Inserting Markets: 100%|██████████| 286/286 [00:00<00:00, 22419.37it/s]

2025-06-10 16:32:30,340 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2025-06-10 16:32:30,341 INFO sqlalchemy.engine.Engine [raw sql] ()
2025-06-10 16:32:30,344 INFO sqlalchemy.engine.Engine select current_schema()
2025-06-10 16:32:30,344 INFO sqlalchemy.engine.Engine [raw sql] ()
2025-06-10 16:32:30,348 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2025-06-10 16:32:30,348 INFO sqlalchemy.engine.Engine [raw sql] ()
2025-06-10 16:32:30,350 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-06-10 16:32:30,353 INFO sqlalchemy.engine.Engine INSERT INTO farmbase_core.market (name, location) SELECT p0::VARCHAR, p1::geometry(POINT,4326) FROM (VALUES ($1::VARCHAR, ST_GeomFromEWKT($2), 0), ($3::VARCHAR, ST_GeomFromEWKT($4), 1), ($5::VARCHAR, ST_GeomFromEWKT($6), 2), ($7::VARCHAR, ST_GeomFrom ... 12596 characters truncated ... , farmbase_core.market.created_at, farmbase_core.market.updated_at, farmbase_core.market.id AS id__1
2025-06-10 16:32:30,354 INFO sqlalchemy.engine.Engine [generated in 0.00036s (insertmanyvalues) 1/1 (ordered)] ('Awendo', 'POINT(34.52846 -0.87469)', 'Aram', 'POINT(35.83546 0.161726)', 'Kababu', 'POINT(37.65 0.05)', 'Elwak Livestock Market', 'POINT(40.8318 2.831778)', 'Akala', 'POINT(34.42605 -0.059466)', 'Kangeta', 'POINT(37.8833 0.2833)', 'Old port Fish Market', 'POINT(39.67955 -4.058054)', 'Elwak Market', 'POINT(40.93211 2.810566)', 'Rongo', 'POINT(34.59862 -0.818652)', 'Kabiyet Market', 'POINT(35.0833 0.4)', 'Ortum', 'POINT(35.35629 1.44038)', 'Kajiado Market', 'POINT(36.78832 -1.841601)', 'Ngong market', 'POINT(36.65675 -1.3598)', 'Taveta', 'POINT(37.6833 -3.4)', 'Katito', 'POINT(34.97325 -0.274214)', 'Garissa Soko Mugdi', 'POINT(40.35641 -0.523633)', 'Kagio', 'POINT(37.25 -0.6166)', 'Marigat', 'POINT(36.03507 0.438553)', 'Masii Crops', 'POINT(37.43919 -1.4608)', 'Eldoret Main', 'POINT(35.27274 0.518128)', 'Takaba Livestock Market', 'POINT(40.2242 3.398734)', 'Isiolo Fresh Produce', 'POINT(38.7479 1.00606)', 'Eldama Ravine', 'POINT(35.73309 -0.01985)', 'Kongowea', 'POINT(39.68691 -4.038018)', 'Karatina', 'POINT(37.12522 -0.482246)' ... 472 parameters truncated ... 'Loyangalani fishing cooperative', 'POINT(36.71673 2.75837)', 'Nanyuki Livestock Market', 'POINT(37.07463 0.01403)', 'Emining Livestock Market', 'POINT(35.8888 0.143695)', 'Kimanjo Livestock Market', 'POINT(37.01109 0.476694)', 'Voi Wholesale', 'POINT(38.8036 -3.559275)', 'Voi Retail', 'POINT(38.8036 -3.559275)', 'Taveta Retail Market', 'POINT(37.6833 -3.4)', 'Mghange', 'POINT(38.31295 -3.40107)', 'Keroka Kisii', 'POINT(34.94715 -0.779212)', 'Rumuruti Food Crops Market', 'POINT(36.54037 0.26903)', 'Mandera Market', 'POINT(40.70562 3.228533)', 'Balambala Livestock Market', 'POINT(39.08199 0.108437)', 'Bondeni', 'POINT(36.08299 -0.293796)', 'Khayega', 'POINT(34.77314 0.206242)', 'Nambacha Market', 'POINT(34.66735 0.394815)', 'Naroosura Livestock Market', 'POINT(35.76971 -1.359155)', 'Isebania Market', 'POINT(34.47922 -1.240322)', 'Sega', 'POINT(34.2258 0.2558)', 'Lamu', 'POINT(40.90106 -2.26754)', 'Tankar Market', 'POINT(40.05 1.75)', 'Kimumu - Bahati', 'POINT(35.28855 0.545695)', 'Butere Livestock Market', 'POINT(34.49813 0.216308)', 'Bomet Market', 'POINT(35.23996 -0.719605)', 'Kipini Fish market', 'POINT(40.52725 -2.528173)', 'Cheptulu', 'POINT(34.8646 0.129513)')
2025-06-10 16:32:30,374 INFO sqlalchemy.engine.Engine COMMIT
✅ Finished populating markets.

In [7]:
from pprint import pprint

from farmbase import MarketPrice, Market, Commodity
from sqlalchemy import select

# Create async DB engine and session
# DATABASE_URL = "postgresql+asyncpg://user:pass@localhost/dbname"  # replace with actual
engine = create_async_engine(settings.sqlalchemy_database_uri, echo=True)
AsyncSessionLocal = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)


async def load_market_prices(df: pd.DataFrame):
    """
    Loads market price data from a pandas DataFrame into the database.
    It creates Commodity and Market entries if they don't exist,
    then links MarketPrice records to them.
    Performs lookups to Commodity and Market tables efficiently.
    Uses SQLAlchemy 2.0 style for queries and session management.
    """
    # Use 'with' statement for session management for proper closing
    async with AsyncSessionLocal() as session:
        try:
            # Convert 'Date' column to datetime.date objects
            df["Date"] = pd.to_datetime(df["Date"], errors="coerce").dt.date

            # --- Pre-load existing Markets ---
            print("Pre-loading existing Markets...")
            # Use await session.execute(select(Market))
            result = await session.execute(select(Market))
            market_lookup = {market.name: market for market in result.scalars().all()}
            print(f"Found {len(market_lookup)} existing markets.")

            # --- Pre-load existing Commodities ---
            print("Pre-loading existing Commodities...")
            commodity_lookup = {}
            # Use await session.execute(select(Commodity))
            result = await session.execute(select(Commodity))
            for commodity in result.scalars().all():
                sex_value = commodity.sex.value if commodity.sex else None
                commodity_lookup[(commodity.name, commodity.classification, commodity.grade, sex_value)] = commodity
            print(f"Found {len(commodity_lookup)} existing commodities.")
            pprint(commodity_lookup)

            for index, row in df.iterrows():
                # --- Handle Market Lookup/Creation ---
                market_name = row["Market"]
                market_obj = market_lookup.get(market_name)

                if not market_obj:
                    print(f"no market with name: {market_name}, {row}")
                    continue

                # --- Handle Commodity Lookup/Creation ---
                commodity_name = row["Commodity"]
                if pd.isna(commodity_name):
                    print(f"No commodity name: {row}")
                    continue
                classification = row["Classification"] if pd.notna(row["Classification"]) else None
                grade = row["Grade"] if pd.notna(row["Grade"]) else None

                sex_str = None if pd.isna(row["Sex"]) else row["Sex"].lower()
                commodity_key = (commodity_name, classification, grade, sex_str)
                commodity_obj = commodity_lookup.get(commodity_key)

                if not commodity_obj:
                    raise Exception(f"no commodity with key: {commodity_key}")

                # --- Create MarketPrice entry ---
                market_price_obj = MarketPrice(
                    market_id=market_obj.id,
                    commodity_id=commodity_obj.id,
                    date=row["Date"],
                    supply_volume=row["Supply Volume"] if pd.notna(row["Supply Volume"]) else None,
                    wholesale_price=row["wholesale_price"] if pd.notna(row["wholesale_price"]) else None,
                    wholesale_unit=row["wholesale_unit"] if pd.notna(row["wholesale_unit"]) else None,
                    wholesale_ccy=row["wholesale_ccy"] if pd.notna(row["wholesale_ccy"]) else None,
                    retail_price=row["retail_price"] if pd.notna(row["retail_price"]) else None,
                    retail_unit=row["retail_unit"] if pd.notna(row["retail_unit"]) else None,
                    retail_ccy=row["retail_ccy"] if pd.notna(row["retail_ccy"]) else None,
                )
                session.add(market_price_obj)

            await session.commit()  # Await commit
            print("\nSuccessfully loaded all market prices into the database.")

        except Exception as e:
            await session.rollback()
            print(f"\nAn error occurred: {e}. Rolling back transaction.")
        # 'finally' block is not needed with 'with' statement for session.close() as it's handled automatically


await load_market_prices(
    df.drop_duplicates(subset=["Market", "Commodity", "Classification", "Grade", "Sex", "Date"], keep="first")
)

Pre-loading existing Markets...
2025-06-20 14:41:32,906 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2025-06-20 14:41:32,906 INFO sqlalchemy.engine.Engine [raw sql] ()
2025-06-20 14:41:32,910 INFO sqlalchemy.engine.Engine select current_schema()
2025-06-20 14:41:32,910 INFO sqlalchemy.engine.Engine [raw sql] ()
2025-06-20 14:41:32,914 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2025-06-20 14:41:32,914 INFO sqlalchemy.engine.Engine [raw sql] ()
2025-06-20 14:41:32,916 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-06-20 14:41:32,950 INFO sqlalchemy.engine.Engine SELECT farmbase_core.market.id, farmbase_core.market.name, ST_AsEWKB(farmbase_core.market.location) AS location, farmbase_core.market.created_at, farmbase_core.market.updated_at
FROM farmbase_core.market
2025-06-20 14:41:32,951 INFO sqlalchemy.engine.Engine [generated in 0.00066s] ()
Found 286 existing markets.
Pre-loading existing Commodities...
2025-06-20 14:41:32,989 INFO sqlalchemy.engine.Engine SELECT farmbase_core.commodity.id, farmbase_core.commodity.name, farmbase_core.commodity.classification, farmbase_core.commodity.grade, farmbase_core.commodity.sex
FROM farmbase_core.commodity
2025-06-20 14:41:32,989 INFO sqlalchemy.engine.Engine [generated in 0.00038s] ()

/var/folders/5d/c4d7d1814b33g1r6_cn3h87w0000gn/T/ipykernel_79913/3975772009.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce").dt.date

Found 808 existing commodities.
{('African butter catfish', 'Dried', None, None): <Commodity(id=538, name='African butter catfish')>,
 ('African butter catfish', 'Fresh', None, None): <Commodity(id=402, name='African butter catfish')>,
 ('African butter catfish', 'Frozen/Chilled', None, None): <Commodity(id=642, name='African butter catfish')>,
 ('African butter catfish', 'Smoked', None, None): <Commodity(id=567, name='African butter catfish')>,
 ('Alestes', 'Dried', None, None): <Commodity(id=467, name='Alestes')>,
 ('Amaranthus (Terere)', None, None, None): <Commodity(id=72, name='Amaranthus (Terere)')>,
 ('Anchovies', 'Dried', None, None): <Commodity(id=500, name='Anchovies')>,
 ('Anchovies', 'Fresh', None, None): <Commodity(id=339, name='Anchovies')>,
 ('Apples', 'Green', None, None): <Commodity(id=266, name='Apples')>,
 ('Apples', 'Red', None, None): <Commodity(id=279, name='Apples')>,
 ('Apples', None, None, None): <Commodity(id=120, name='Apples')>,
 ('Arrow Root', None, None, 'male'): <Commodity(id=257, name='Arrow Root')>,
 ('Arrow Root', None, None, None): <Commodity(id=96, name='Arrow Root')>,
 ('Avocado', None, None, 'male'): <Commodity(id=240, name='Avocado')>,
 ('Avocado', 'Fuerte', None, None): <Commodity(id=98, name='Avocado')>,
 ('Avocado', 'Hass', None, None): <Commodity(id=150, name='Avocado')>,
 ('Avocado', 'Local', None, None): <Commodity(id=58, name='Avocado')>,
 ('Avocado', None, None, None): <Commodity(id=219, name='Avocado')>,
 ('Banana (Cooking)', None, None, None): <Commodity(id=108, name='Banana (Cooking)')>,
 ('Banana (Plantain)', None, None, None): <Commodity(id=110, name='Banana (Plantain)')>,
 ('Banana (Ripening)', 'Cooking Banana', None, None): <Commodity(id=220, name='Banana (Ripening)')>,
 ('Banana (Ripening)', 'Cooking Banana', None, 'male'): <Commodity(id=241, name='Banana (Ripening)')>,
 ('Banana (Ripening)', 'Ripe Banana', None, None): <Commodity(id=221, name='Banana (Ripening)')>,
 ('Banana (Ripening)', None, None, None): <Commodity(id=57, name='Banana (Ripening)')>,
 ('Barbus', 'Dried', None, None): <Commodity(id=653, name='Barbus')>,
 ('Barracuda(Kasumba)', 'Dried', None, None): <Commodity(id=664, name='Barracuda(Kasumba)')>,
 ('Barracuda(Kasumba)', 'Fresh', None, None): <Commodity(id=337, name='Barracuda(Kasumba)')>,
 ('Barracuda(Kasumba)', 'Fried', None, None): <Commodity(id=334, name='Barracuda(Kasumba)')>,
 ('Beans (Canadian wonder)', None, None, 'male'): <Commodity(id=262, name='Beans (Canadian wonder)')>,
 ('Beans (Canadian wonder)', None, None, None): <Commodity(id=2, name='Beans (Canadian wonder)')>,
 ('Beans (Mwezi Moja)', None, None, None): <Commodity(id=1, name='Beans (Mwezi Moja)')>,
 ('Beans (Mwitemania)', None, None, None): <Commodity(id=126, name='Beans (Mwitemania)')>,
 ('Beans (Yellow-Green)', None, None, None): <Commodity(id=82, name='Beans (Yellow-Green)')>,
 ('Beans Red Haricot (Wairimu)', None, None, 'male'): <Commodity(id=261, name='Beans Red Haricot (Wairimu)')>,
 ('Beans Red Haricot (Wairimu)', None, None, None): <Commodity(id=118, name='Beans Red Haricot (Wairimu)')>,
 ('Beans Rosecoco', None, None, 'male'): <Commodity(id=260, name='Beans Rosecoco')>,
 ('Beans Rosecoco', None, None, None): <Commodity(id=81, name='Beans Rosecoco')>,
 ('Beans Rosecoco (Nyayo)', None, None, None): <Commodity(id=79, name='Beans Rosecoco (Nyayo)')>,
 ('Black bass', 'Dried', None, None): <Commodity(id=403, name='Black bass')>,
 ('Black bass', 'Fresh', None, None): <Commodity(id=302, name='Black bass')>,
 ('Black bass', 'Frozen/Chilled', None, None): <Commodity(id=793, name='Black bass')>,
 ('Black bass', 'Smoked', None, None): <Commodity(id=794, name='Black bass')>,
 ('Black nightshade (Managu/ Osuga)', None, None, 'male'): <Commodity(id=237, name='Black nightshade (Managu/ Osuga)')>,
 ('Black nightshade (Managu/ Osuga)', None, None, None): <Commodity(id=71, name='Black nightshade (Managu/ Osuga)')>,
 ('Broccoli', None, None, None): <Commodity(id=136, name='Broccoli')>,
 ('Butternuts', None, None, None): <Commodity(id=135, name='Butternuts')>,
 ('Cabbages', None, None, 'male'): <Commodity(id=243, name='Cabbages')>,
 ('Cabbages', None, None, None): <Commodity(id=86, name='Cabbages')>,
 ('Camel', 'Gabra/Redille', 'Grade 1 ', 'female'): <Commodity(id=550, name='Camel')>,
 ('Camel', 'Gabra/Redille', 'Grade 1 ', 'male'): <Commodity(id=517, name='Camel')>,
 ('Camel', 'Gabra/Redille', 'Grade 2', 'female'): <Commodity(id=580, name='Camel')>,
 ('Camel', 'Gabra/Redille', 'Grade 2', 'male'): <Commodity(id=527, name='Camel')>,
 ('Camel', 'Gabra/Redille', 'Grade 3', 'female'): <Commodity(id=603, name='Camel')>,
 ('Camel', 'Gabra/Redille', 'Grade 3', 'male'): <Commodity(id=484, name='Camel')>,
 ('Camel', 'Gabra/Redille', 'Grade 4', 'female'): <Commodity(id=539, name='Camel')>,
 ('Camel', 'Gabra/Redille', 'Grade 4', 'male'): <Commodity(id=558, name='Camel')>,
 ('Camel', 'Somali', 'Grade 1 ', 'castrate'): <Commodity(id=541, name='Camel')>,
 ('Camel', 'Somali', None, 'male'): <Commodity(id=547, name='Camel')>,
 ('Camel', 'Somali', 'Grade 2', 'castrate'): <Commodity(id=577, name='Camel')>,
 ('Camel', 'Somali', 'Grade 3', 'female'): <Commodity(id=555, name='Camel')>,
 ('Camel', 'Turkana', 'Grade 1 ', 'male'): <Commodity(id=533, name='Camel')>,
 ('Camel', 'Turkana', 'Grade 2', 'male'): <Commodity(id=562, name='Camel')>,
 ('Camel', 'Turkana', None, 'male'): <Commodity(id=570, name='Camel')>,
 ('Camel', 'Turkana', 'Grade 1 ', 'castrate'): <Commodity(id=604, name='Camel')>,
 ('Camel', 'Turkana', 'Grade 1 ', 'female'): <Commodity(id=584, name='Camel')>,
 ('Camel', 'Turkana', 'Grade 2', 'female'): <Commodity(id=606, name='Camel')>,
 ('Camel', None, None, 'male'): <Commodity(id=607, name='Camel')>,
 ('Camel', 'Gabra/Redille', 'Grade 1 ', 'castrate'): <Commodity(id=733, name='Camel')>,
 ('Camel', 'Gabra/Redille', None, 'female'): <Commodity(id=737, name='Camel')>,
 ('Camel', 'Gabra/Redille', None, 'male'): <Commodity(id=734, name='Camel')>,
 ('Camel', 'Somali', 'Grade 1 ', 'female'): <Commodity(id=331, name='Camel')>,
 ('Camel', 'Somali', 'Grade 1 ', 'male'): <Commodity(id=174, name='Camel')>,
 ('Camel', 'Somali', 'Grade 2', 'female'): <Commodity(id=323, name='Camel')>,
 ('Camel', 'Somali', 'Grade 2', 'male'): <Commodity(id=270, name='Camel')>,
 ('Camel', 'Somali', 'Grade 3', 'male'): <Commodity(id=316, name='Camel')>,
 ('Camel', 'Somali', 'Grade 4', 'female'): <Commodity(id=315, name='Camel')>,
 ('Camel', 'Somali', 'Grade 4', 'male'): <Commodity(id=271, name='Camel')>,
 ('Camel', 'Turkana', 'Grade 2', 'castrate'): <Commodity(id=619, name='Camel')>,
 ('Camel', 'Turkana', 'Grade 3', 'female'): <Commodity(id=691, name='Camel')>,
 ('Camel', 'Turkana', 'Grade 3', 'male'): <Commodity(id=729, name='Camel')>,
 ('Camel', 'Turkana', 'Grade 4', 'male'): <Commodity(id=735, name='Camel')>,
 ('Camel', None, 'Grade 1 ', 'female'): <Commodity(id=749, name='Camel')>,
 ('Camel', None, 'Grade 1 ', 'male'): <Commodity(id=702, name='Camel')>,
 ('Camel', None, 'Grade 2', 'male'): <Commodity(id=748, name='Camel')>,
 ('Camel Hide', None, 'Grade 1', None): <Commodity(id=674, name='Camel Hide')>,
 ('Camel Hide', None, 'Grade 2', None): <Commodity(id=698, name='Camel Hide')>,
 ('Camel Hide', None, 'Grade 3', None): <Commodity(id=775, name='Camel Hide')>,
 ('Camel Milk(At collection point)', None, None, None): <Commodity(id=37, name='Camel Milk(At collection point)')>,
 ('Camel meat', None, None, None): <Commodity(id=38, name='Camel meat')>,
 ('Camel milk(Processed)', None, None, None): <Commodity(id=267, name='Camel milk(Processed)')>,
 ('Capsicums', None, None, None): <Commodity(id=90, name='Capsicums')>,
 ('Carrots', None, None, 'male'): <Commodity(id=252, name='Carrots')>,
 ('Carrots', None, None, None): <Commodity(id=94, name='Carrots')>,
 ('Cashewnuts (Korosho)', None, None, None): <Commodity(id=805, name='Cashewnuts (Korosho)')>,
 ('Cassava Chips (dry)', None, None, None): <Commodity(id=51, name='Cassava Chips (dry)')>,
 ('Cassava Fresh', None, None, None): <Commodity(id=50, name='Cassava Fresh')>,
 ('Cat Fish(Mkizi/Fume)', 'Chilled', None, None): <Commodity(id=332, name='Cat Fish(Mkizi/Fume)')>,
 ('Cat Fish(Mkizi/Fume)', 'Dried', None, None): <Commodity(id=378, name='Cat Fish(Mkizi/Fume)')>,
 ('Cat Fish(Mkizi/Fume)', None, None, None): <Commodity(id=609, name='Cat Fish(Mkizi/Fume)')>,
 ('Cat Fish(Mkizi/Fume)', 'Fresh', None, None): <Commodity(id=46, name='Cat Fish(Mkizi/Fume)')>,
 ('Cat Fish(Mkizi/Fume)', 'Frozen', None, None): <Commodity(id=632, name='Cat Fish(Mkizi/Fume)')>,
 ('Cat Fish(Mkizi/Fume)', 'Headless and Gutted', None, None): <Commodity(id=405, name='Cat Fish(Mkizi/Fume)')>,
 ('Cat Fish(Mkizi/Fume)', 'Smoked', None, None): <Commodity(id=317, name='Cat Fish(Mkizi/Fume)')>,
 ('Cattle', None, 'Grade 2', 'female'): <Commodity(id=216, name='Cattle')>,
 ('Cattle', 'Ayrshire', None, 'female'): <Commodity(id=186, name='Cattle')>,
 ('Cattle', 'Ayrshire', 'Grade 1 ', 'female'): <Commodity(id=275, name='Cattle')>,
 ('Cattle', 'Ayrshire', 'Grade 1 ', 'male'): <Commodity(id=329, name='Cattle')>,
 ('Cattle', 'Ayrshire', 'Grade 2', 'female'): <Commodity(id=276, name='Cattle')>,
 ('Cattle', 'Boran', 'Grade 1 ', 'female'): <Commodity(id=147, name='Cattle')>,
 ('Cattle', 'Boran', 'Grade 2', 'female'): <Commodity(id=322, name='Cattle')>,
 ('Cattle', 'Boran', 'Grade 2', 'male'): <Commodity(id=296, name='Cattle')>,
 ('Cattle', 'Boran', 'Grade 4 ', 'male'): <Commodity(id=308, name='Cattle')>,
 ('Cattle', 'Mixed', None, 'castrate'): <Commodity(id=215, name='Cattle')>,
 ('Cattle', 'Mixed', None, 'female'): <Commodity(id=199, name='Cattle')>,
 ('Cattle', None, None, 'male'): <Commodity(id=207, name='Cattle')>,
 ('Cattle', 'Boran', 'Grade 5', 'male'): <Commodity(id=234, name='Cattle')>,
 ('Cattle', 'Mixed', 'Grade 1 ', 'female'): <Commodity(id=159, name='Cattle')>,
 ('Cattle', 'Mixed', 'Grade 1 ', 'male'): <Commodity(id=297, name='Cattle')>,
 ('Cattle', 'Mixed', 'Grade 2', 'female'): <Commodity(id=178, name='Cattle')>,
 ('Cattle', 'Mixed', 'Grade 2', 'male'): <Commodity(id=197, name='Cattle')>,
 ('Cattle', 'Mixed', 'Grade 5', 'female'): <Commodity(id=229, name='Cattle')>,
 ('Cattle', 'Mixed', 'Grade 5', 'male'): <Commodity(id=157, name='Cattle')>,
 ('Cattle', 'Mixed', None, 'male'): <Commodity(id=156, name='Cattle')>,
 ('Cattle', 'Other', 'Grade 1 ', 'female'): <Commodity(id=170, name='Cattle')>,
 ('Cattle', 'Other', 'Grade 5', 'male'): <Commodity(id=169, name='Cattle')>,
 ('Cattle', 'Sahiwal', 'Grade 1 ', 'male'): <Commodity(id=290, name='Cattle')>,
 ('Cattle', 'Sahiwal', 'Grade 2', 'male'): <Commodity(id=289, name='Cattle')>,
 ('Cattle', 'Zebu', 'Grade 1 ', 'female'): <Commodity(id=182, name='Cattle')>,
 ('Cattle', 'Zebu', 'Grade 1 ', 'male'): <Commodity(id=288, name='Cattle')>,
 ('Cattle', 'Zebu', 'Grade 3 ', 'male'): <Commodity(id=153, name='Cattle')>,
 ('Cattle', 'Zebu', 'Grade 4 ', 'female'): <Commodity(id=155, name='Cattle')>,
 ('Cattle', 'Zebu', 'Grade 4 ', 'male'): <Commodity(id=154, name='Cattle')>,
 ('Cattle', 'Zebu', 'Grade 5', 'female'): <Commodity(id=177, name='Cattle')>,
 ('Cattle', 'Zebu', 'Grade 5', 'male'): <Commodity(id=176, name='Cattle')>,
 ('Cattle', None, 'Grade 1 ', 'female'): <Commodity(id=307, name='Cattle')>,
 ('Cattle', None, 'Grade 1 ', 'male'): <Commodity(id=299, name='Cattle')>,
 ('Cattle', None, 'Grade 2', 'male'): <Commodity(id=303, name='Cattle')>,
 ('Cattle', 'Ayrshire', 'Grade 2', 'castrate'): <Commodity(id=503, name='Cattle')>,
 ('Cattle', 'Ayrshire', 'Grade 2', 'male'): <Commodity(id=476, name='Cattle')>,
 ('Cattle', 'Ayrshire', 'Grade 3 ', 'castrate'): <Commodity(id=514, name='Cattle')>,
 ('Cattle', 'Ayrshire', 'Grade 4 ', 'female'): <Commodity(id=318, name='Cattle')>,
 ('Cattle', 'Ayrshire', 'Grade 4 ', 'male'): <Commodity(id=658, name='Cattle')>,
 ('Cattle', 'Ayrshire', None, 'male'): <Commodity(id=706, name='Cattle')>,
 ('Cattle', 'Boran', 'Grade 1 ', 'castrate'): <Commodity(id=620, name='Cattle')>,
 ('Cattle', 'Boran', 'Grade 2', 'castrate'): <Commodity(id=581, name='Cattle')>,
 ('Cattle', 'Boran', 'Grade 3 ', 'castrate'): <Commodity(id=601, name='Cattle')>,
 ('Cattle', 'Exotic', 'Grade 2', 'female'): <Commodity(id=488, name='Cattle')>,
 ('Cattle', 'Exotic', 'Grade 2', 'male'): <Commodity(id=526, name='Cattle')>,
 ('Cattle', 'Exotic', 'Grade 3 ', 'female'): <Commodity(id=627, name='Cattle')>,
 ('Cattle', 'Exotic', 'Grade 4 ', 'female'): <Commodity(id=544, name='Cattle')>,
 ('Cattle', 'Exotic', 'Grade 4 ', 'male'): <Commodity(id=535, name='Cattle')>,
 ('Cattle', 'Friesian', 'Grade 1 ', 'female'): <Commodity(id=321, name='Cattle')>,
 ('Cattle', 'Friesian', 'Grade 1 ', 'male'): <Commodity(id=328, name='Cattle')>,
 ('Cattle', 'Friesian', 'Grade 2', 'castrate'): <Commodity(id=507, name='Cattle')>,
 ('Cattle', 'Friesian', 'Grade 2', 'male'): <Commodity(id=486, name='Cattle')>,
 ('Cattle', 'Friesian', 'Grade 3 ', 'castrate'): <Commodity(id=518, name='Cattle')>,
 ('Cattle', 'Friesian', 'Grade 3 ', 'female'): <Commodity(id=479, name='Cattle')>,
 ('Cattle', 'Friesian', 'Grade 3 ', 'male'): <Commodity(id=477, name='Cattle')>,
 ('Cattle', 'Friesian', 'Grade 4 ', 'castrate'): <Commodity(id=478, name='Cattle')>,
 ('Cattle', 'Friesian', 'Grade 4 ', 'female'): <Commodity(id=520, name='Cattle')>,
 ('Cattle', 'Friesian', None, 'male'): <Commodity(id=705, name='Cattle')>,
 ('Cattle', 'Guernsey ', 'Grade 1 ', 'female'): <Commodity(id=633, name='Cattle')>,
 ('Cattle', 'Guernsey ', 'Grade 1 ', 'male'): <Commodity(id=469, name='Cattle')>,
 ('Cattle', 'Guernsey ', 'Grade 2', 'female'): <Commodity(id=505, name='Cattle')>,
 ('Cattle', 'Guernsey ', 'Grade 2', 'male'): <Commodity(id=582, name='Cattle')>,
 ('Cattle', 'Other', 'Grade 1 ', 'castrate'): <Commodity(id=618, name='Cattle')>,
 ('Cattle', 'Other', 'Grade 2', 'castrate'): <Commodity(id=617, name='Cattle')>,
 ('Cattle', None, 'Grade 3 ', 'castrate'): <Commodity(id=622, name='Cattle')>,
 ('Cattle', 'Guernsey ', 'Grade 3 ', 'female'): <Commodity(id=645, name='Cattle')>,
 ('Cattle', 'Guernsey ', 'Grade 3 ', 'male'): <Commodity(id=497, name='Cattle')>,
 ('Cattle', 'Guernsey ', 'Grade 4 ', 'female'): <Commodity(id=482, name='Cattle')>,
 ('Cattle', 'Mixed', 'Grade 1 ', 'castrate'): <Commodity(id=354, name='Cattle')>,
 ('Cattle', 'Mixed', 'Grade 3 ', 'castrate'): <Commodity(id=602, name='Cattle')>,
 ('Cattle', 'Mixed', 'Grade 3 ', 'female'): <Commodity(id=325, name='Cattle')>,
 ('Cattle', 'Mixed', 'Grade 3 ', 'male'): <Commodity(id=319, name='Cattle')>,
 ('Cattle', 'Mixed', 'Grade 4 ', 'male'): <Commodity(id=509, name='Cattle')>,
 ('Cattle', 'Other', 'Grade 1 ', 'male'): <Commodity(id=309, name='Cattle')>,
 ('Cattle', 'Other', 'Grade 3 ', 'castrate'): <Commodity(id=659, name='Cattle')>,
 ('Cattle', 'Other', 'Grade 3 ', 'female'): <Commodity(id=563, name='Cattle')>,
 ('Cattle', 'Other', 'Grade 3 ', 'male'): <Commodity(id=564, name='Cattle')>,
 ('Cattle', 'Other', 'Grade 4 ', 'female'): <Commodity(id=699, name='Cattle')>,
 ('Cattle', 'Other', 'Grade 4 ', 'male'): <Commodity(id=661, name='Cattle')>,
 ('Cattle', 'Sahiwal', 'Grade 2', 'castrate'): <Commodity(id=588, name='Cattle')>,
 ('Cattle', 'Sahiwal', 'Grade 3 ', 'castrate'): <Commodity(id=504, name='Cattle')>,
 ('Cattle', 'Sahiwal', 'Grade 3 ', 'female'): <Commodity(id=502, name='Cattle')>,
 ('Cattle', 'Sahiwal', 'Grade 4 ', 'female'): <Commodity(id=489, name='Cattle')>,
 ('Cattle', 'Sahiwal', 'Grade 4 ', 'male'): <Commodity(id=487, name='Cattle')>,
 ('Cattle', 'Sahiwal', None, 'castrate'): <Commodity(id=491, name='Cattle')>,
 ('Cattle', 'Sahiwal', None, 'male'): <Commodity(id=510, name='Cattle')>,
 ('Cattle', 'Sahiwal', 'Grade 4 ', 'castrate'): <Commodity(id=708, name='Cattle')>,
 ('Cattle', 'Somali spotted', 'Grade 1 ', 'male'): <Commodity(id=578, name='Cattle')>,
 ('Cattle', 'Somali spotted', 'Grade 2', 'castrate'): <Commodity(id=597, name='Cattle')>,
 ('Cattle', 'Somali spotted', 'Grade 2', 'female'): <Commodity(id=598, name='Cattle')>,
 ('Cattle', 'Somali spotted', 'Grade 2', 'male'): <Commodity(id=599, name='Cattle')>,
 ('Cattle', 'Somali spotted', 'Grade 3 ', 'castrate'): <Commodity(id=686, name='Cattle')>,
 ('Cattle', 'Somali spotted', 'Grade 3 ', 'female'): <Commodity(id=600, name='Cattle')>,
 ('Cattle', 'Somali spotted', 'Grade 3 ', 'male'): <Commodity(id=585, name='Cattle')>,
 ('Cattle', 'Zebu', 'Grade 1 ', 'castrate'): <Commodity(id=532, name='Cattle')>,
 ('Cattle', 'Zebu', 'Grade 2', 'castrate'): <Commodity(id=310, name='Cattle')>,
 ('Cattle', 'Zebu', 'Grade 3 ', 'castrate'): <Commodity(id=499, name='Cattle')>,
 ('Cattle', 'Zebu', 'Grade 4 ', 'castrate'): <Commodity(id=513, name='Cattle')>,
 ('Cattle', None, 'Grade 1 ', 'castrate'): <Commodity(id=700, name='Cattle')>,
 ('Cattle', None, 'Grade 2', 'castrate'): <Commodity(id=561, name='Cattle')>,
 ('Cattle', None, 'Grade 3 ', 'female'): <Commodity(id=326, name='Cattle')>,
 ('Cattle', None, 'Grade 3 ', 'male'): <Commodity(id=327, name='Cattle')>,
 ('Cattle', None, 'Grade 4 ', 'female'): <Commodity(id=536, name='Cattle')>,
 ('Cattle', None, 'Grade 4 ', 'male'): <Commodity(id=537, name='Cattle')>,
 ('Cattle', 'Boran', None, 'female'): <Commodity(id=716, name='Cattle')>,
 ('Cattle', 'Exotic', None, 'female'): <Commodity(id=753, name='Cattle')>,
 ('Cattle', 'Sahiwal', None, 'female'): <Commodity(id=746, name='Cattle')>,
 ('Cattle', 'Somali spotted', 'Grade 4 ', 'castrate'): <Commodity(id=741, name='Cattle')>,
 ('Cattle', 'Somali spotted', 'Grade 4 ', 'male'): <Commodity(id=715, name='Cattle')>,
 ('Cattle', None, None, 'female'): <Commodity(id=719, name='Cattle')>,
 ('Cattle', 'Ayrshire', 'Grade 1 ', 'castrate'): <Commodity(id=774, name='Cattle')>,
 ('Cattle', 'Ayrshire', 'Grade 3 ', 'female'): <Commodity(id=374, name='Cattle')>,
 ('Cattle', 'Ayrshire', 'Grade 3 ', 'male'): <Commodity(id=367, name='Cattle')>,
 ('Cattle', 'Boran', 'Grade 4 ', 'female'): <Commodity(id=397, name='Cattle')>,
 ('Cattle', 'Exotic', 'Grade 1 ', 'female'): <Commodity(id=379, name='Cattle')>,
 ('Cattle', 'Exotic', 'Grade 1 ', 'male'): <Commodity(id=380, name='Cattle')>,
 ('Cattle', 'Exotic', 'Grade 3 ', 'male'): <Commodity(id=375, name='Cattle')>,
 ('Cattle', 'Exotic', None, 'male'): <Commodity(id=763, name='Cattle')>,
 ('Cattle', 'Friesian', None, 'female'): <Commodity(id=557, name='Cattle')>,
 ('Cattle', 'Friesian', 'Grade 1 ', 'castrate'): <Commodity(id=769, name='Cattle')>,
 ('Cattle', 'Friesian', 'Grade 2', 'female'): <Commodity(id=387, name='Cattle')>,
 ('Cattle', 'Friesian', 'Grade 4 ', 'male'): <Commodity(id=792, name='Cattle')>,
 ('Cattle', 'Gabra/Redille', 'Grade 1 ', 'male'): <Commodity(id=777, name='Cattle')>,
 ('Cattle', 'Mixed', 'Grade 2', 'castrate'): <Commodity(id=377, name='Cattle')>,
 ('Cattle', 'Mixed', 'Grade 4 ', 'female'): <Commodity(id=336, name='Cattle')>,
 ('Cattle', 'Other', 'Grade 2', 'female'): <Commodity(id=559, name='Cattle')>,
 ('Cattle', 'Other', 'Grade 2', 'male'): <Commodity(id=560, name='Cattle')>,
 ('Cattle', 'Sahiwal', 'Grade 1 ', 'castrate'): <Commodity(id=365, name='Cattle')>,
 ('Cattle', 'Sahiwal', 'Grade 1 ', 'female'): <Commodity(id=363, name='Cattle')>,
 ('Cattle', 'Sahiwal', 'Grade 2', 'female'): <Commodity(id=364, name='Cattle')>,
 ('Cattle', 'Sahiwal', 'Grade 3 ', 'male'): <Commodity(id=396, name='Cattle')>,
 ('Cattle', 'Somali spotted', 'Grade 1 ', 'female'): <Commodity(id=784, name='Cattle')>,
 ('Cattle', 'Somali spotted', 'Grade 4 ', 'female'): <Commodity(id=714, name='Cattle')>,
 ('Cattle', 'Zebu', 'Grade 1', 'female'): <Commodity(id=721, name='Cattle')>,
 ('Cattle', None, 'Grade 4 ', 'castrate'): <Commodity(id=799, name='Cattle')>,
 ('Cattle', None, 'Grade 5', 'male'): <Commodity(id=115, name='Cattle')>,
 ('Cattle', 'Boran', 'Grade 1 ', 'male'): <Commodity(id=47, name='Cattle')>,
 ('Cattle', 'Boran', 'Grade 3 ', 'female'): <Commodity(id=103, name='Cattle')>,
 ('Cattle', 'Boran', 'Grade 3 ', 'male'): <Commodity(id=102, name='Cattle')>,
 ('Cattle', 'Boran', None, 'male'): <Commodity(id=45, name='Cattle')>,

In [35]:
print()